# Generated by Django 3.2.4 on 2021-12-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
            options={
                'verbose_name': 'hora',
                'verbose_name_plural': 'horas',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppReserva.timer'),
        ),
    ]
